{{- $fullName := include "acend-training-chart.fullname" . -}}
{{- $all := . -}}
{{- range .Values.acendTraining.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- include "acend-training-chart.labels" $all | nindent 4 }}
    app.kubernetes.io/name: {{ include "acend-training-chart.name" $all }}-{{ .name }}
  annotations:
    timestamp: {{ now | quote }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "acend-training-chart.selectorLabels" $all | nindent 6 }}
      app.kubernetes.io/name: {{ include "acend-training-chart.name" $all }}-{{ .name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "acend-training-chart.selectorLabels" $all | nindent 8 }}
        app.kubernetes.io/name: {{ include "acend-training-chart.name" $all }}-{{ .name }}
    spec:
      serviceAccountName: {{ include "acend-training-chart.serviceAccountName" $all }}
      containers:
        - name: training
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          image: "{{ .image.repository }}:{{ .image.tag | default $all.Release.Name }}{{ .image.tagsuffix | default "" }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 2
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 20m
              memory: 56Mi
{{- end }}