{{- $fullName := include "acend-training-chart.fullname" . -}}
{{- $svcPort := .Values.acendTraining.servicePort -}}
{{- $releaseName := .Release.Name -}}
{{- $all := . -}}
{{- range .Values.acendTraining.deployments }}
{{- $hostname := "" }}
{{- if or (eq $releaseName "main") (eq $releaseName "latest") }}
{{- $domain := default .ingress.domain .ingress.domainmain }}
{{- $hostname = printf "%s%s%s" .ingress.appname "." $domain }}
{{- else }}
{{- $hostname = printf "%s%s%s%s%s" .ingress.appname "-" $releaseName "." .ingress.domain }}
{{- end }}
{{- $secretName := .ingress.secretOverride }}
{{- if not $secretName }}
{{- $secretName = printf "%s%s%s" $fullName "-" .name  }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- include "acend-training-chart.labels" $all | nindent 4 }}
    app.kubernetes.io/name: {{ include "acend-training-chart.name" $all }}-{{ .name }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - "{{ $hostname }}"
      {{- if not .ingress.useDefaultSecret }}
      secretName: {{ $secretName | replace "." "-" }}
      {{- end }}
  rules:
    - host: "{{ $hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-{{ .name }}
                port:
                  number: {{ $svcPort }}
{{- end }}