{{- if .Values.route.create -}}
{{- $fullName := include "acend-training-chart.fullname" . -}}
{{- $svcPort := .Values.acendTraining.servicePort -}}
{{- $releaseName := .Release.Name -}}
{{- $all := . -}}
{{- range .Values.acendTraining.deployments }}
{{- $hostname := "" }}
{{- if or (eq $releaseName "main") (eq $releaseName "latest") }}
{{- $domain := default .ingress.domain .ingress.domainmain }}
{{- $hostname = printf "%s%s%s" .ingress.appname "." $domain }}
{{- else }}
{{- $hostname = printf "%s%s%s%s%s" .ingress.appname "-" $releaseName "." .ingress.domain }}
{{- end }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- include "acend-training-chart.labels" $all | nindent 4 }}
    app.kubernetes.io/name: {{ include "acend-training-chart.name" $all }}-{{ .name }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: "{{ $hostname }}"
  to:
    kind: Service
    name: {{ $fullName }}-{{ .name }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
{{- end }}