{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acend-training-chart.serviceAccountName" . }}
  labels:
    {{- include "acend-training-chart.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "acend-training-chart.name" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
