{{- $fullName := include "acend-training-chart.fullname" . -}}
{{- $svcPort := .Values.acendTraining.servicePort -}}
{{- $all := . -}}
{{- range .Values.acendTraining.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- include "acend-training-chart.labels" $all | nindent 4 }}
    app.kubernetes.io/name: {{ include "acend-training-chart.name" $all }}-{{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svcPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "acend-training-chart.selectorLabels" $all | nindent 4 }}
    app.kubernetes.io/name: {{ include "acend-training-chart.name" $all }}-{{ .name }}
{{- end }}