acendTraining:
  servicePort: 8080
  deployments:

    - name: acend
      replicaCount: 1
      image:
        repository: quay.io/acend/hugo-training-template
        pullPolicy: Always
        tag: "latest"
        tagprefix: ""
        tagsuffix: ""
      podLabels: {}
      podAnnotations: {}
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx-public
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: acend-letsencrypt
        # secretOverride: secretName
        # Adds an empty TLS configuration, e.g., for use on OpenShift with wildcard certificates
        emptyTLS: false
        useDefaultSecret: false
        appname: hugo-training-template
        domain: training.acend.ch

    - name: puzzle
      replicaCount: 1
      image:
        repository: quay.io/acend/hugo-training-template
        pullPolicy: Always
        tag: "latest"
        tagprefix: ""
        tagsuffix: "-puzzle"
      podLabels: {}
      podAnnotations: {}
      ingress:
        annotations:
          kubernetes.io/tls-acme: "true"
        # ingressClassName: nginx
        useDefaultSecret: true
        appname: hugo-training-template
        domain: training.acend.ch
        # domainmain: puzzle.ch

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
